#!/usr/bin/env python3
"""Generate thin <wx/...> headers that forward to the compatibility layer."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src" / "wx_stub" / "wx"

HEADERS = [
    "app.h",
    "arrstr.h",
    "artprov.h",
    "aui/auibar.h",
    "aui/aui.h",
    "base64.h",
    "bitmap.h",
    "bmpbuttn.h",
    "brush.h",
    "busyinfo.h",
    "button.h",
    "checkbox.h",
    "choicdlg.h",
    "choice.h",
    "choicebk.h",
    "clipbrd.h",
    "cmdline.h",
    "colordlg.h",
    "colour.h",
    "collpane.h",
    "combo.h",
    "config.h",
    "control.h",
    "cursor.h",
    "dataobj.h",
    "datetime.h",
    "dcbuffer.h",
    "dcclient.h",
    "dcmemory.h",
    "dc.h",
    "defs.h",
    "dialog.h",
    "dirctrl.h",
    "dir.h",
    "display.h",
    "dnd.h",
    "event.h",
    "eventfilter.h",
    "evtloop.h",
    "fdrepdlg.h",
    "fileconf.h",
    "filedlg.h",
    "filefn.h",
    "file.h",
    "filename.h",
    "frame.h",
    "gdicmn.h",
    "glcanvas.h",
    "grid.h",
    "hashmap.h",
    "html/htmlwin.h",
    "icon.h",
    "image.h",
    "ipc.h",
    "listbook.h",
    "listctrl.h",
    "log.h",
    "menu.h",
    "menuitem.h",
    "minifram.h",
    "msgdlg.h",
    "mstream.h",
    "notebook.h",
    "numdlg.h",
    "object.h",
    "panel.h",
    "pen.h",
    "progdlg.h",
    "protocol/http.h",
    "radiobox.h",
    "regex.h",
    "scrolwin.h",
    "settings.h",
    "sharedptr.h",
    "sizer.h",
    "slider.h",
    "snglinst.h",
    "spinctrl.h",
    "splitter.h",
    "sstream.h",
    "statbmp.h",
    "statline.h",
    "stattext.h",
    "statusbr.h",
    "stdpaths.h",
    "stopwatch.h",
    "stream.h",
    "string.h",
    "textctrl.h",
    "textdlg.h",
    "tglbtn.h",
    "thread.h",
    "timer.h",
    "tipwin.h",
    "tokenzr.h",
    "toolbar.h",
    "toolbook.h",
    "treectrl.h",
    "txtstrm.h",
    "url.h",
    "utils.h",
    "vector.h",
    "vlbox.h",
    "wfstream.h",
    "window.h",
    "wx.h",
    "wxhtml.h",
    "wxprec.h",
    "xml/xml.h",
    "zstream.h",
]


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    for rel in HEADERS:
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "#pragma once\n"
            "// Auto-generated wxWidgets stub. Real types live in <wx/compat.h>.\n"
            "#include <wx/compat.h>\n",
            encoding="utf-8",
        )
    print(f"Wrote {len(HEADERS)} wx stub headers under {ROOT}")


if __name__ == "__main__":
    main()
